[package]
name = "rust_physical_engine"
version = "0.1.0"
authors = ["Elanis <contact@elanis.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13"